apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
spec:
  replicas: 1
  imagePullSecrets:
    - name: acr-secret
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
        - name: samplewebapp 
          image: acr112233.azurecr.io/samplewebapp
          ports:
          - containerPort: 80
